# Generated by Django 5.2.5 on 2025-08-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_coldstorecapacity_usertype_document_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='businessrelationship',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='businessrelationship',
            name='primary_user',
        ),
        migrations.RemoveField(
            model_name='businessrelationship',
            name='secondary_user',
        ),
        migrations.DeleteModel(
            name='ColdStoreCapacity',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='user',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='pricingmodel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pricingmodel',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_type',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text='Business address', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='business_type',
            field=models.CharField(blank=True, help_text='Type of business', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company name for corporate users', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the user account has been verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin (Super User)'), ('b2c_visitor', 'B2C (Visitor)'), ('corporate', 'Corporate'), ('horeca', 'HoReCa'), ('supplier', 'Supplier'), ('supplier_merchant', 'Supplier and Merchant'), ('storage_client', 'Storage Client')], default='b2c_visitor', help_text='User type determines permissions and access levels', max_length=50),
        ),
        migrations.DeleteModel(
            name='BusinessRelationship',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='PricingModel',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
