# Generated by Django 5.2.5 on 2025-08-20 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(help_text='Product name in English', max_length=200)),
                ('name_ar', models.CharField(help_text='Product name in Arabic', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Product image', null=True, upload_to='products/')),
                ('description_en', models.TextField(blank=True, help_text='Product description in English', null=True)),
                ('description_ar', models.TextField(blank=True, help_text='Product description in Arabic', null=True)),
                ('category', models.CharField(blank=True, help_text='Product category', max_length=100, null=True)),
                ('subcategory', models.CharField(blank=True, help_text='Product subcategory', max_length=100, null=True)),
                ('unit', models.CharField(default='KG', help_text='Unit of measurement (KG, Package, etc.)', max_length=50)),
                ('unit_size', models.DecimalField(decimal_places=2, default=1.0, help_text='Size of the unit (e.g., 1.0 for 1 KG, 20.0 for 20 KG package)', max_digits=10)),
                ('end_user_price', models.DecimalField(decimal_places=2, help_text='End user price - retail market price (e.g., 150 L.E for 1 KG)', max_digits=10)),
                ('retail_price_b2c', models.DecimalField(decimal_places=2, help_text='Retail price for B2C wholesale (e.g., 2000 L.E for 20 KG package)', max_digits=10)),
                ('retail_price_corporate', models.DecimalField(decimal_places=2, help_text='Retail price for corporates/purchasing managers (e.g., 1850 L.E for 20 KG package)', max_digits=10)),
                ('retail_price_horeca', models.DecimalField(decimal_places=2, help_text='Retail price for HoReCa businesses (e.g., 1900 L.E for 20 KG package)', max_digits=10)),
                ('wholesale_price', models.DecimalField(decimal_places=2, help_text='Wholesale price for bulk orders (e.g., 1800 L.E for 20 KG package, min 5 packages)', max_digits=10)),
                ('wholesale_min_quantity', models.PositiveIntegerField(default=5, help_text='Minimum quantity required for wholesale price')),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Available stock quantity')),
                ('is_available', models.BooleanField(default=True, help_text='Product availability status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('supplier', models.ForeignKey(help_text='Product supplier', limit_choices_to={'role__in': ['supplier', 'supplier_merchant']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, unique=True)),
                ('name_ar', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productcategory')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'db_table': 'product_category',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/additional/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='products.product')),
            ],
            options={
                'db_table': 'product_image',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_available'], name='product_categor_9473b3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['supplier', 'is_available'], name='product_supplie_8ac22c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_deleted'], name='product_is_dele_ac0796_idx'),
        ),
    ]
